services:

  tmserver:
    image: mcarigs/tmserver
    container_name: tmserver
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    volumes:
      - ./xaseco:/var/lib/xaseco
      - ./tracks:/var/lib/tmserver/GameData/Tracks/Challenges/Custom  # Custom tracks
      - ./music:/var/lib/tmserver/GameData/Music                      # Custom music
      - ./playlist.txt:/var/lib/tmserver/playlist.txt                 # Custom track playlist
      - ./blacklist:/var/lib/xaseco/blacklist                         # Plugin blacklist
      - ./plugins:/var/lib/xaseco/plugins/custom                      # Custom plugins
      - ./config:/var/lib/xaseco/config                               # Custom configuration files
    ports:
      - "2350:2350/udp"
      - "2350:2350/tcp"
      - "3450:3450/udp"
      - "3450:3450/tcp"
    networks:
      - trackmania

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - trackmania

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: trackmania
      MYSQL_PASSWORD: password
      MYSQL_LOGIN: trackmania
    restart: always
    ports:
      - "8080:80"
    networks:
      - trackmania

networks:
  trackmania:

volumes:
  db_data:
